apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-board-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-board-frontend
  template:
    metadata:
      labels:
        app: message-board-frontend
    spec:
      containers:
      - name: message-board-frontend
        image: docker.io/xmadking/message_board_frontend:latest
        ports:
        - containerPort: 5000
        env:
        - name: BACKEND_URL
          value: http://message-board-backend:5000
