apiVersion: v1
kind: Service
metadata:
  name: message_board_frontend
spec:
  selector:
    app: message_board_frontend
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30080
  type: NodePort