apiVersion: v1
kind: Service
metadata:
  name: message-board-frontend
spec:
  selector:
    app: message-board-frontend
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30080
  type: NodePort