@startuml overview

package "Kubernetes" as K8s {
  database db
  rectangle backend_1
  label "..." as mult_back
  rectangle backend_n
  rectangle frontend_1
  label "..." as mult_front
  rectangle frontend_n

  interface "ClusterIP" as db_interface

  db <-- db_interface

  db_interface <-- backend_1
  db_interface <-- mult_back
  db_interface <-- backend_n

  interface "ClusterIP" as backend_interface

  backend_1 <-- backend_interface
  mult_back <-- backend_interface
  backend_n <-- backend_interface

  backend_interface <-- frontend_1
  backend_interface <-- mult_front
  backend_interface <-- frontend_n

  interface NodePort

  frontend_1 <-- NodePort
  mult_front <-- NodePort
  frontend_n <-- NodePort
}

actor "Browser" as browser

NodePort <-- browser

@enduml
